version: "3"
services:
  app:
    container_name: red-admin-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: 'mysql:8'
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
    networks:
      - app-network

volumes:
  my-db: null

networks:
  app-network:
    driver: bridge