version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: 'mysql:8'
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
    networks:
      - app-network

volumes:
  my-db: null

networks:
  app-network:
    driver: bridge