version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: 'mysql:8'
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
    networks:
      - app-network

volumes:
  my-db: null

networks:
  app-network:
    driver: bridge