definitions:
  apiv1.UrlRequest:
    properties:
      destination:
        type: string
      label:
        type: string
    required:
    - destination
    - label
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Url:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      destination:
        type: string
      id:
        type: integer
      label:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/url:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Url'
            type: array
      summary: Get urls list
  /api/v1/url/:
    post:
      consumes:
      - application/json
      parameters:
      - description: URL label
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/apiv1.UrlRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiv1.UrlRequest'
      summary: Create new url
  /api/v1/url/{id}:
    delete:
      parameters:
      - description: Url ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Delete an existing url
    get:
      consumes:
      - application/json
      parameters:
      - description: Url ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiv1.UrlRequest'
      summary: Get a single url
    put:
      consumes:
      - application/json
      parameters:
      - description: Url ID
        in: path
        name: id
        required: true
        type: integer
      - description: URL label
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/apiv1.UrlRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiv1.UrlRequest'
      summary: Update an existing url
swagger: "2.0"
