info:
  contact: {}
paths:
  /api/v1/articles/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: Get a single article
swagger: "2.0"
